In [14]:
# From a list
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)


0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


### Martix Multiplication

In [15]:
import numpy as np
import pandas as pd

In [16]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])  
print(a.shape)
print(b.shape)

c = a * b

print(c)
d = np.dot(a, b)   
print(d)


(2, 2)
(2, 2)
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [17]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [2]:
import requests 


In [2]:
import math as mp
rad = mp.radians(90)
print(mp.sin(rad))

1.0
