### Numpy

In [2]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

In [ ]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
c = np.array([ [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
b = np.hstack((a, c))

print(" horizental stacking via hstack in numpy",b)

 horizental stacking via hstack in numpy [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [20]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
c = np.array([ [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
b = np.vstack((a, c))

print(" vertical  stacking via hstack in numpy",b)

 vertical  stacking via hstack in numpy [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [33]:
a = np.random.rand(142, 54)
print(a)

[[0.25753234 0.79863723 0.98658143 ... 0.36406194 0.5308289  0.83268054]
 [0.5646458  0.32776631 0.75636275 ... 0.07784885 0.3869674  0.11598618]
 [0.44443117 0.59527881 0.18857402 ... 0.26464204 0.47243849 0.51811153]
 ...
 [0.76268484 0.18119026 0.71600303 ... 0.4623777  0.85584089 0.32127002]
 [0.85297854 0.86834813 0.62923827 ... 0.68202517 0.23791296 0.82633032]
 [0.39190204 0.42551585 0.90126058 ... 0.74471402 0.53136527 0.04050403]]


In [15]:
n = np.random.randint(3, 9, size=(8, 9))
print(n)
print(n.shape)
print(n.size)
print(n.dtype)
print(n.min())
print(n.max())
print(np.sin(n))

[[4 7 8 4 7 8 7 6 8]
 [5 6 4 5 4 4 3 8 3]
 [8 7 3 5 5 4 4 3 5]
 [5 7 5 7 6 5 5 7 4]
 [8 6 4 8 8 7 6 4 7]
 [8 3 7 4 3 4 6 7 6]
 [6 7 3 5 8 6 7 3 6]
 [7 5 6 3 4 8 4 8 3]]
(8, 9)
72
int32
3
8
[[-0.7568025   0.6569866   0.98935825 -0.7568025   0.6569866   0.98935825
   0.6569866  -0.2794155   0.98935825]
 [-0.95892427 -0.2794155  -0.7568025  -0.95892427 -0.7568025  -0.7568025
   0.14112001  0.98935825  0.14112001]
 [ 0.98935825  0.6569866   0.14112001 -0.95892427 -0.95892427 -0.7568025
  -0.7568025   0.14112001 -0.95892427]
 [-0.95892427  0.6569866  -0.95892427  0.6569866  -0.2794155  -0.95892427
  -0.95892427  0.6569866  -0.7568025 ]
 [ 0.98935825 -0.2794155  -0.7568025   0.98935825  0.98935825  0.6569866
  -0.2794155  -0.7568025   0.6569866 ]
 [ 0.98935825  0.14112001  0.6569866  -0.7568025   0.14112001 -0.7568025
  -0.2794155   0.6569866  -0.2794155 ]
 [-0.2794155   0.6569866   0.14112001 -0.95892427  0.98935825 -0.2794155
   0.6569866   0.14112001 -0.2794155 ]
 [ 0.6569866  -0.95892427